name: Build Angular Project

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Angular App (client only)
        run: npm run build -- --configuration=production

      - name: Create or Switch to 'build' Branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin

          # If 'build' exists, check it out; otherwise create it
          if git show-ref --verify --quiet refs/remotes/origin/build; then
            git checkout build
          else
            git checkout -b build
          fi

          # Remove everything in the build branch
          git rm -rf .

          # Copy ONLY the contents of dist/browser into the root of this branch.
          #rt
          cp -r dist/browser/. .

          git add .
          git commit -m "Update build output"
          git push origin build --force
